### ISSUE TITLE
文档错误

### ISSUE THREAD

**Issue by newcovid** [ANGJustinl/nonebot_plugin_face2cartoonpic_main#4]
首先命令是人像变换
其次,在bot.py文件里的加载指令错了,你给加载到戒色打卡里了

**Comment by ANGJustinl** [comment]
是的我忘改了！实在是抱歉

**Comment by ANGJustinl** [comment]
我本地改完没传readme

**Comment by newcovid** [comment]
识别率有些堪忧(我key输入没问题),他说我不是人.,而且好像不支持回复带图,会报错,我用的版本是nonebot2的b5版
![%SHY T7(V8$US{HO{5{6H7S](https://user-images.githubusercontent.com/96228495/210074987-eff14101-ba59-440b-b3b9-94f7d87b2cef.png)
![image](https://user-images.githubusercontent.com/96228495/210075660-b9a16030-9641-4389-a492-b88b8cafa481.png)

**Comment by newcovid** [comment]
而且文档没改全,命令示例里还是人物变换

**Comment by ANGJustinl** [comment]
我觉得可能是key和id的问题，腾讯虽然不支持二次元但是人像识别率还是在那的，你去包的config.py里面手动把key和id填进去试试，然后回复带图在我这里是支持的，你可以再试一下
![image](https://user-images.githubusercontent.com/96008766/210075612-12f07d41-e37b-4a98-affc-875b45e016c0.png)

**Comment by newcovid** [comment]
我长逝一下

**Comment by ANGJustinl** [comment]
这个报错是exception = 2 就是腾讯接口没有返回东西，分api密钥错误和图像不是人像两种

**Comment by ANGJustinl** [comment]
我给bot输出加了没给log加可能不方便查错

**Comment by newcovid** [comment]
确实是我key的问题,我的.env文件好像出BUG了,后面加的配置都不生效,上一个插件也没生效,我还以为是他的问题,现在看来是我的env出了问题

**Comment by ANGJustinl** [comment]
是的我自己试的时候也发现有的人的env配置失效，你可以看看env文件有没有把环境路径设置到.env.dev的

**Comment by ANGJustinl** [comment]
#7 在nb群水群偶然看到了大家也有一样的问题
