### ISSUE TITLE
这个插件是否需要某些依赖？

### ISSUE THREAD

**Issue by aknyzsd** [ANGJustinl/nonebot_plugin_face2cartoonpic_main#5]
插件配置完成后没有问题但是不能使用，是否需要某些依赖？（nonebot显示import插件了env配置也是正确的）

**Comment by ANGJustinl** [comment]
需要的依赖如下
![image](https://user-images.githubusercontent.com/96008766/215308296-e1e176de-fa95-4695-8ccc-a5e8b7fa74d4.png)
但是这是在安装这个插件时自动安装的，而且根据目前收到的反馈应该是不会出现缺失依赖的问题的。
你能检查一下插件的安装情况(如重新安装插件，或打开bot logger的debug模式看看插件有没有被正确加载)
或者给我截个图看看也行

**Comment by aknyzsd** [comment]
插件被成功加载了，不过在安装插件后每次启动都有一句
none of pytorch, tensorflow >= 2.0, or flax have been found. models won't be available and only tokenizers, configuration and file/data utilities can be use
这样的提示，插件在输入命令后没有反应，加/之类的命令头试过了

**Comment by ANGJustinl** [comment]
你这为什么会有pytourch啊，这个插件全部依靠腾讯云接口处理图像不需要你本地运算啊

**Comment by aknyzsd** [comment]
有可能是和别的插件冲突了吧

**Comment by ANGJustinl** [comment]
要不你单独用这个插件试试

**Comment by ANGJustinl** [comment]
pytouch估计是语音合成之类的
