### ISSUE TITLE
key填入没错，还是提示画图失败,输入的不是人像(或api密钥错误)

### ISSUE THREAD

**Issue by WeiLanKing** [ANGJustinl/nonebot_plugin_face2cartoonpic_main#6]
`key输入成功
证书签名如下
[b'6yght85z0XwoHq1hdS5jqJBeCAQ=']
<Response [200]>
输入的不是人像
02-02 20:46:31 [ERROR] nonebot_plugin_face2cartoonpic | 画图失败,输入的不是人像(或api密钥错误)
 error2
02-02 20:46:32 [INFO] nonebot | Matcher(type='message', module=nonebot_plugin_face2cartoonpic) running complete`
不知道哪里的问题

**Comment by ANGJustinl** [comment]
#4 你要不看看这个issue的情况，这个报错可能是你config有问题

**Comment by ANGJustinl** [comment]
https://github.com/ANGJustinl/nonebot_plugin_face2cartoonpic_main/issues/4#issuecomment-1367924772

**Comment by ANGJustinl** [comment]
https://github.com/ANGJustinl/nonebot_plugin_face2cartoonpic_main/issues/7 在nb群水群偶然看到了大家也有一样的问题
